routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DB::listen(function ($query)
// {
//     echo "<pre>{ $query->sql }</pre>";
// });

/**
 * Account Routes
 */
Route::resource('accounts', 'Account\AccountController', ['only' => ['index', 'destroy']]);
Route::post('accounts/{account}', 'Account\AccountController@setAccount')->name('accounts.set_account');

/**
 * Assistance Routes
 */
Route::resource('assistances', 'Assistance\AssistanceController', ['only' => ['store']]);

/**
 * Auth Routes
 */
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

/**
 * Career Routes
 */
Route::resource('careers', 'Career\CareerController', ['only' => ['index']]);
Route::resource('careers.courses', 'Career\CareerCourseController', ['except' => 'show']);
Route::get('careers/{career}', 'Career\CareerController@subjects')->name('careers.subject');
Route::get('careers/{career}/subjects/{subject}', 'Career\CareerController@groups')->name('careers.subjects.group');

/**
 * Course Routes
 */
Route::resource('courses.practices', 'Course\CoursePracticeController', ['only' => ['index']]);
Route::resource('courses.inscriptions', 'Course\CourseInscriptionController', ['only' => ['index']]);
Route::delete('courses/{course}/teachers/{teacher}', 'Course\CourseController@deleteCourse')->name('courses.teachers.delete');
Route::get('courses/{course}', 'Course\CourseInscriptionPracticeController@showCourseInscriptionPractices')->name('courses.inscriptions.practices.show');

/**
 * Group Routes
 */
Route::resource('groups', 'Group\GroupController', ['only' => ['store']]);

/**
 * Home Routes
 */
Route::get('/home', 'HomeController@index')->name('home');

/**
 * Inscription Routes
 */
Route::get('inscriptions/{inscription}', 'Inscription\InscriptionController@deliveredPractice')->name('inscriptions.practice');

/**
 * Main Routes
 */
Route::get('/', function () {
    return view('auth.login');
});

/**
 * Personal Informations Routes
 */
Route::resource('personalInformations', 'Personal_Information\Personal_InformationController');

/**
 * Period Routes
 */
Route::resource('periods', 'Period\PeriodController', ['except' => ['create', 'show', 'edit']]);

/**
 * Practice Routes
 */
Route::resource('practices', 'Practice\PracticeController');
Route::delete('practices/{practice}/registereds/{registered}', 'Practice\PracticeController@deletePractice')->name('practices.registereds.delete');

/**
 * Subject Routes
 */
Route::get('subjects/{subject}/careers/{career}', 'Subject\SubjectController@periods')->name('subjects.careers.period');

/**
 * User Routes
 */
Route::resource('users', 'User\UserController');
Route::put('users/{user}', 'User\UserController@updatePassword')->name('users.password');
Route::name('verify')->get('users/verify/{token}', 'User\UserController@verify');

app/User.php
<?php

namespace App;

use App\Career;
use App\Account;
use App\Student;
use App\Teacher;
use App\Personal_Information;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    const VERIFIED = '1';
    const NO_VERIFIED = '0';

    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'user_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'password',
        'remember_token',
        'verified',
        'verification_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 
        'remember_token',
        'verification_token',
    ];

    public function userVerified()
    {
        return $this->verified = User::VERIFIED;
    }

    public static function generateVerificationToken()
    {
        return str_random(40);
    }

    public function student()
    {
        return $this->hasOne(Student::class, 'user_id');
    }

    public function teacher()
    {
        return $this->hasOne(Teacher::class, 'user_id');
    }

    public function personalInformation()
    {
        return $this->hasOne(Personal_Information::class, 'user_id');
    }

    public function accounts()
    {
        return $this->hasMany(Account::class, 'user_id');
    }

    public function hasRoles(array $roles)
    {
        foreach ($this->accounts()->with('roles')->get()->pluck('roles') as $userRoles) {
            return $userRoles->pluck('role_name')->intersect($roles)->count();
        }

        // foreach ($this->accounts()->with('roles')->get()->pluck('roles') as $userRoles) {
        //     foreach ($userRoles as  $userRole) {
        //         foreach ($roles as $role) {
        //             if ($userRole->role_name === $role) {
        //                 return true;
        //             }
        //         }
        //     }
        // }

        return false;
    }

    public function isAdmin()
    {
        return $this->hasRoles(['Maestro']);
    }

    public function countRoles()
    {
        return $this->accounts()->with('roles')->get()->pluck('roles')->collapse()->count();
    }

    public static function setAccountsData($data)
    {
        $career = Career::findOrFail($data['career_id']);

        $personalInformation = new Personal_Information([
            'user_id' => $data['user_id'],
            'name' => $data['name'],
            'last_name' => $data['last_name'],
            'last_mother_name' => $data['last_mother_name'],
            'email' => $data['email'],
            'phone' => $data['phone'],
            'gender' => $data['gender'],
        ]);

        $user = User::create([
            'user_id' => $data['user_id'],
            'password' => bcrypt($data['password']),
            'verified' => User::NO_VERIFIED,
            'verification_token' => User::generateVerificationToken(),
        ]);
        $user->personalInformation()->save($personalInformation);

        $account = new Account([
            'career_id' => $career->career_id,
            'user_id' => $user->user_id,
        ]);
        $account->generatePk();
        $user->accounts()->save($account);

        return $user;
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('roles:Maestro')->except('verify', 'updatePassword');
        $this->middleware('auth')->except('verify');
    }

    public function index()
    {
        $users = DB::table('users')
                ->join('personal__informations', 'users.user_id', '=', 'personal__informations.user_id')
                ->join('accounts', 'users.user_id', '=', 'accounts.user_id')
                ->join('careers', 'accounts.career_id', '=', 'careers.career_id')
                ->join('account_rol', 'accounts.account_id', '=', 'account_rol.account_id')
                ->join('roles', 'account_rol.role_id', '=', 'roles.role_id')
                ->join('students', 'users.user_id', '=', 'students.user_id')
                ->join('inscriptions', 'students.user_id', '=', 'inscriptions.user_id')
                ->join('courses', 'inscriptions.course_id', '=', 'courses.course_id')
                ->join('subjects', 'courses.subject_id', '=', 'subjects.subject_id')
                ->select('personal__informations.*', 'careers.career_name', 'careers.career_id', 'roles.role_name', 
                            DB::raw("GROUP_CONCAT(subjects.subject_name ORDER BY subjects.subject_name SEPARATOR ', ') as subjects"))
                ->groupBy('personal__informations.user_id')
                ->get();

        return view('users.user-show', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    public function verify($verifcationToken)
    {
        $user = User::where('verification_token', $verifcationToken)->firstOrFail();
        $user->verified = User::VERIFIED;
        $user->verification_token = null;

        $user->save();

        return redirect('/')->with('success', 'Tu correo ha sido verificado, por favor espera a que el profesor valide tu cuenta');
    }

    public function updatePassword(Request $request, User $user)
    {
       $rules = [
           'old_password' => 'required',
           'password' => 'required|min:6|confirmed'
       ];

       $this->validate($request, $rules);

       if (Hash::check($request->old_password, $user->password)) {
           $user->password = Hash::make($request->password);
           $user->save();
           return back()->with('info', 'La contraseña a sido cambiada');
       } else {
           return back()->with('danger', 'Error la contraseña introduccida es erronea!');
       }
    }
}

resources/views/users/user-requests.blade.php
@extends('layouts.app')

@section('section')
    Peticiones de Registro
@endsection

@section('content')
    <div class="form-group">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Tabla de peticiones de usuario para tener acceso al sistema.
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr role="row" class="text-center">
                                <th colspan="6">Datos del usuario</th>
                                <th colspan="3">Opciones</th>
                            </tr>
                            <tr role="row">
                                <th>Numero de cuenta</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Telefono</th>
                                <th>Carrera</th>
                                <th>Fecha y hora de Registro</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($usersRequests as $user)
                                <tr class="item{{ $user->user_id }}">
                                    <td>{{ $user->user_id }}</td>
                                    <td>{{ $user->name . ' ' . $user->last_name . ' ' . $user->last_mother_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->phone }}</td>
                                    <td>{{ $user->career_name }}</td>
                                    <td>{{ date('d/m/Y H:m:s', strtotime($user->created_at)) }}</td>
                                    <td>
                                        <button class="btn btn-outline-success nav-link pass-assign" data-toggle="modal" type="button" data-target="#userAssign" data-user-id="{{ $user->user_id }}" data-career-id="{{ $user->career_id }}"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Asignar grupo</button>
                                    </td>
                                    <td>
                                        <button class="btn btn-outline-info assign-teacher" data-user-id="{{ $user->user_id }}" data-career-id="{{ $user->career_id }}" type="submit"><i class="fa fa-coffee" aria-hidden="true"></i> Asignar como profesor</button>    
                                    </td>
                                    <td>
                                        <form method="POST" action="{{ route('accounts.destroy', $user->career_id . $user->user_id) }}">
                                            @csrf
                                            {!! method_field('DELETE') !!}
                                            
                                            <button class="btn btn-outline-danger" type="submit"><i class="fa fa-times-circle-o" aria-hidden="true"></i> Negar petición</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Numero de cuenta</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Telefono</th>
                                <th>Carrera</th>
                                <th>Hora y fecha de Registro</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('users.modals.assign-group')

    @push('crud')
        @include('users.ajax.retrieve_js')
    @endpush

@endsection

resources/views/users/user-show.blade.php
@extends('layouts.app')

@section('section')
    Usuarios Registrados
@endsection

@section('content')
    <div class="form-group">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Tabla de usuarios registrados
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr role="row">
                                <th colspan="8">Datos de cuenta</th>
                                <th colspan="2">Opciones</th>
                            </tr>
                            <tr>
                                <th>Número de cuenta</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Teléfono</th>
                                <th>Carrera</th>
                                <th>Asignaturas</th>
                                <th>Fecha y hora de registro</th>
                                <th>Rol</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                           @foreach ($users as $user)
                           <tr class="item{{ $user->user_id }}">
                                <td>{{ $user->user_id }}</td>
                                <td>{{ $user->name . ' ' . $user->last_name . ' ' . $user->last_mother_name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->phone }}</td>
                                <td>{{ $user->career_name }}</td>
                                <td>{{ $user->subjects }}</td>
                                <td>{{ date('d/m/Y H:m:s', strtotime($user->created_at))}}</td>
                                <td>{{ $user->role_name }}</td>
                                <td>
                                    <button class="btn btn-outline-info nav-link pass-assign" data-toggle="modal" type="button" data-target="#userAssign" data-user-id="{{ $user->user_id }}" data-career-id="{{ $user->career_id }}"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Reasignar otro grupo</button>
                                </td>
                            </tr>
                           @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Número de cuenta</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Teléfono</th>
                                <th>Carrera</th>
                                <th>Asignaturas</th>
                                <th>Fecha y hora de registro</th>
                                <th>Rol</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('users.modals.reassign-group')
    @push('crud')
        @include('users.ajax.retrieve_js')
    @endpush
@endsection