routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DB::listen(function ($query)
// {
//     echo "<pre>{ $query->sql }</pre>";
// });

/**
 * Account Routes
 */
Route::resource('accounts', 'Account\AccountController', ['only' => ['index', 'destroy']]);
Route::post('accounts/{account}', 'Account\AccountController@setAccount')->name('accounts.set_account');

/**
 * Assistance Routes
 */
Route::resource('assistances', 'Assistance\AssistanceController', ['only' => ['store']]);

/**
 * Auth Routes
 */
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

/**
 * Career Routes
 */
Route::resource('careers', 'Career\CareerController', ['only' => ['index']]);
Route::resource('careers.courses', 'Career\CareerCourseController', ['except' => 'show']);
Route::get('careers/{career}', 'Career\CareerController@subjects')->name('careers.subject');
Route::get('careers/{career}/subjects/{subject}', 'Career\CareerController@groups')->name('careers.subjects.group');

/**
 * Course Routes
 */
Route::resource('courses.practices', 'Course\CoursePracticeController', ['only' => ['index']]);
Route::resource('courses.inscriptions', 'Course\CourseInscriptionController', ['only' => ['index']]);
Route::delete('courses/{course}/teachers/{teacher}', 'Course\CourseController@deleteCourse')->name('courses.teachers.delete');
Route::get('courses/{course}', 'Course\CourseInscriptionPracticeController@showCourseInscriptionPractices')->name('courses.inscriptions.practices.show');

/**
 * Group Routes
 */
Route::resource('groups', 'Group\GroupController', ['only' => ['store']]);

/**
 * Home Routes
 */
Route::get('/home', 'HomeController@index')->name('home');

/**
 * Inscription Routes
 */
Route::get('inscriptions/{inscription}', 'Inscription\InscriptionController@deliveredPractice')->name('inscriptions.practice');

/**
 * Main Routes
 */
Route::get('/', function () {
    return view('auth.login');
});

/**
 * Personal Informations Routes
 */
Route::resource('personalInformations', 'Personal_Information\Personal_InformationController');

/**
 * Period Routes
 */
Route::resource('periods', 'Period\PeriodController', ['except' => ['create', 'show', 'edit']]);

/**
 * Practice Routes
 */
Route::resource('practices', 'Practice\PracticeController');
Route::delete('practices/{practice}/registereds/{registered}', 'Practice\PracticeController@deletePractice')->name('practices.registereds.delete');

/**
 * Subject Routes
 */
Route::get('subjects/{subject}/careers/{career}', 'Subject\SubjectController@periods')->name('subjects.careers.period');

/**
 * User Routes
 */
Route::resource('users', 'User\UserController');
Route::put('users/{user}', 'User\UserController@updatePassword')->name('users.password');
Route::name('verify')->get('users/verify/{token}', 'User\UserController@verify');

app/Career.php
<?php

namespace App;

use App\Course;
use App\Account;
use Illuminate\Database\Eloquent\Model;

class Career extends Model
{
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'career_id';

    protected $fillable = [
    	'career_id',
    	'career_name',
    ];

    public function accounts()
    {
    	return $this->hasMany(Account::class, 'career_id');
    }

    public function courses()
    {
    	return $this->hasMany(Course::class, 'career_id');
    }

    public function subjects(){
        return $this->hasMany(Subject::class, 'career_id')->orderBy('subject_name');
    }
}

app/Http/Controllers/Career/CareerController.php
<?php

namespace App\Http\Controllers\Career;

use Response;
use App\Career;
use App\Course;
use App\Period;
use App\Subject;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class CareerController extends Controller
{

    function __construct(){
        $this->middleware('roles:Maestro');
        $this->middleware('auth')->except('subjects, groups');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $careers = Career::all();

        return view('shared._navbar', compact('careers'));
    }

    /**
     * Retrieve subjects to career
     *
     * @param  \App\Career  $career
     */
    public function subjects(Career $career)
    {
        $courses = DB::table('courses')
                    ->join('subjects', 'courses.subject_id', '=', 'subjects.subject_id')
                    ->select('subjects.subject_id', 'subjects.subject_name')
                    ->where('courses.career_id', '=', $career->career_id)
                    ->distinct()
                    ->get();

        return Response::json($courses);
    }

     /**
     * Retrieve subjects to career
     *
     * @param  \App\Career  $career
     * @param  \App\Subject  $subject
     */
    public function groups(Career $career, Subject $subject)
    {
        $groups = Course::select('group_id')
                    ->where('career_id', $career->career_id)
                    ->where('subject_id', $subject->subject_id)
                    ->get();
        return Response::json($groups);
    }
}

app/Http/Controllers/Career/CareerCourseController.php
<?php

namespace App\Http\Controllers\Career;

use App\Group;
use App\Career;
use App\Course;
use App\Period;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Teacher;
use App\Registered;

class CareerCourseController extends Controller
{

    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('roles:Maestro');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Career $career)
    {
        $subjects = $career->courses()->with('subjects')->get();

        return view('careers.career-show', compact('career', 'subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Career $career)
    {
        $subjects = $career->subjects;
        $periods = Period::all();

        return view('courses.course-create', compact('career', 'subjects', 'periods'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Career $career)
    {
        $rules = [
            'period_id' => 'required',
            'subject_id' => 'required',
            'group_id' => 'required|size:4'
        ];

        $this->validate($request, $rules);

       Course::create([
           'course_id' => $career->career_id . $request->input('period_id') . $request->input('subject_id') . $request->input('group_id'),
           'career_id' => $career->career_id,
           'period_id' => $request->input('period_id'),
           'subject_id' => $request->input('subject_id'),
           'group_id' => $request->input('group_id')
       ]);

       $course = new Course(['career_id' => $career->career_id, 'period_id' => $request->input('period_id'), 'subject_id' => $request->input('subject_id'), 'group_id' => $request->input('group_id')]);
       $course->generatePK();

       if (auth()->check()) {
           $teacher = Teacher::findorFail(auth()->user()->user_id);

           $registered_id = $course->course_id . $teacher->user_id;
           $teacher->courses()->attach($course->course_id, ['registered_id' => $registered_id, 'user_id' => $teacher->user_id]);
       }

       //redirect
       return redirect()->route('careers.courses.index', $career->career_id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function edit(Career $career, Course $course)
    {
        $subject = $course->subjects;
        $periods = Period::all();
        
        return view('courses.course-edit', compact('career', 'subject','periods', 'course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Career $career, Course $course)
    {
        $rules = [
            'period_id' => 'required',
            'group_id' => 'required|size:4',
            'justification' => 'required|min:10'
        ];

        $this->validate($request, $rules);

        $course->course_id = $course->generatePK($career->career_id . $request->input('period_id') . $course->subject_id . $request->input('group_id'));
        $course->career_id = $career->career_id;
        $course->period_id = $request->input('period_id');
        $course->subject_id = $course->subject_id;
        $course->group_id = $request->input('group_id');

        $course->save();
 
        return redirect()->route('careers.courses.index', $career->career_id);
    }
}

resources/views/careers/career-show.blade.php
@extends('layouts.app')

{{-- The menu items are set --}}
@section('section')
    Carreras
@endsection
@section('show')
    <li class="breadcrumb-item active">
       {{ $career->career_name }}
    </li>
@endsection

{{-- Creation of the table for show courses --}}
@section('content')
<div class="form-group">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Tabla de Cursos
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th colspan="8">
                                <a name="newCourse" id="" class="btn btn-outline-primary btn-block" href="{{ route('careers.courses.create', $career->career_id) }}" role="button">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Nuevo Curso
                                </a>
                            </th>
                        </tr>
                        <tr role="row" class="text-center">
                            <th colspan="4">Datos del Curso</th>
                            <th colspan="4">Acciones</th>
                        </tr>
                        <tr role="row">
                            <th>Carrera</th>
                            <th>Grupo</th>
                            <th>Asignatura</th>
                            <th>Periodo</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($subjects as $subject)
                            <tr class="item{{ $loop->iteration }}">
                                <td>{{ $career->career_name }}</td>
                                <td>{{ $subject->group_id }}</td>
                                <td>{{ $subject->subjects->subject_name }}</td>
                                <td>{{ $subject->period_id }}</td>
                                <td>
                                    <a class="btn btn-outline-info" href="{{ route('courses.inscriptions.index', $subject->course_id) }}" role="button"><i class="fa fa-sign-in" aria-hidden="true"></i> Alumnos Inscritos</a>
                                </td>
                                <td class="text-center">
                                <a href="{{ route('courses.practices.index', $subject->course_id) }}" role="button" class="btn btn-outline-success">
                                        <i class="fa fa-flash" aria-hidden="true"></i> Gestionar 
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('careers.courses.edit',['career' => $career->career_id, 'course' => $subject->course_id]) }}" role="button" class="btn btn-outline-warning">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                                    <a>
                                </td>
                                <td class="text-center">
                                    <a role="button" href="#" class="btn btn-outline-danger nav-link delete-course" data-toggle="modal" data-target="#deleteCourse" data-course-id="{{ $subject->course_id }}" data-position="{{ $loop->iteration }}" data-user-id="{{ auth()->user()->user_id }}"><i class="fa fa-ban" aria-hidden="true"></i> Eliminar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Carrera</th>
                            <th>Grupo</th>
                            <th>Asignatura</th>
                            <th>Periodo</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@include('courses/modals.course-delete')

@push('crud')
    @include('courses.ajax.crud_js')
@endpush

@endsection